name: $(BuildDefinitionName).$(Build.BuildId)

trigger: none

variables:
  Environment: catch22-$(Build.BuildId)
  WorkingDirectory: $(System.DefaultWorkingDirectory)/catch-22-msi-sql

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: TerraformCLI@0
    displayName: Initialise Terraform
    inputs:
      command: init
      workingDirectory: $(WorkingDirectory)/terraform
      
  - task: TerraformCLI@0
    displayName: Create Terraform plan
    inputs:
      command: plan
      workingDirectory: $(WorkingDirectory)/terraform
      environmentServiceName: $(PipelineServiceConnection)
      commandOptions: -out=tf.plan
    env:
      TF_VAR_environment_name: $(Environment)

  - task: TerraformCLI@0
    displayName: Terraform environment
    inputs:
      command: apply
      workingDirectory: $(WorkingDirectory)/terraform
      environmentServiceName: $(PipelineServiceConnection)
      commandOptions: tf.plan